<h2 align=center> Principal Component Analysis</h2>

### Task 2: Load the Data and Libraries
---

In [ ]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
plt.style.use("ggplot")
plt.rcParams["figure.figsize"] = (12,8)

In [ ]:
# data URL: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

In [1]:
df = pd.read_excel (r'D:\Course\AI & Machine learning\Data Science\Session 4 Noteboks\Excel_Sample.xlsx')
print (df)

NameError: ignored

### Task 3: Visualize the Data
---

In [3]:
import plotly.express as px
df = px.data.iris()
fig = px.scatter_3d(df, x='sepal_length', y='sepal_width', z='petal_width',
              color='species')
fig.show()

### Task 4: Standardize the Data
---

In [4]:
# df2=
df["sepal_length"]=df["sepal_length"]*100
df["sepal_width"]=df["sepal_width"]*100
df["petal_width"]=df["petal_width"]*100

fig = px.scatter_3d(df, x='sepal_length', y='sepal_width', z='petal_width',
              color='species')
fig.show()


### Task 5: Compute the Eigenvectors and Eigenvalues
---

Covariance: $\sigma_{jk} = \frac{1}{n-1}\sum_{i=1}^{N}(x_{ij}-\bar{x_j})(x_{ik}-\bar{x_k})$

Coviance matrix: $Σ = \frac{1}{n-1}((X-\bar{x})^T(X-\bar{x}))$

In [5]:
import numpy as np
from numpy.linalg import eig
a = np.array([[0, 5], 
              [3, 8]])

We can prove this by looking at the covariance matrix. It has the property that it is symmetric. We also constrain the each of the columns (eigenvectors) such that the values sum to one. Thus, they are orthonormal to each other.

Eigendecomposition of the covriance matrix:  $Σ = W\wedge W^{-1}$

In [6]:
w,v=eig(a)
print('E-value = ', w)
print('E-vector = ', v)

E-value =  [-1.56776436  9.56776436]
E-vector =  [[-0.95419352 -0.46315735]
 [ 0.29919012 -0.88627607]]


### Task 6: Singular Value Decomposition (SVD)
---

In [7]:
import numpy as np
 
#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
 
#Performing SVD
U, D, VT = np.linalg.svd(A)
 
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)
print(A_remake)


[[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


### Task 7: Picking Principal Components Using the Explained Variance
---

### Task 8: Project Data Onto Lower-Dimensional Linear Subspace
---